package za.co.cas;

public enum Subject implements Comparable<Subject> {
    HOME_LANGUAGE, FIRST_ADDITIONAL_LANGUAGE, SECOND_ADDITIONAL_LANGUAGE, MATHEMATICS, MATHEMATICAL_LITERACY,
    TECHNICAL_MATHEMATICS, LIFE_ORIENTATION, PHYSICAL_SCIENCE, LIFE_SCIENCES, ARCHITECTURAL_SCIENCE, ELECTRICAL_SCIENCE,
    TECHNICAL_SCIENCE, SOCIAL_SCIENCES, INFORMATION_TECHNOLOGY, COMPUTER_AND_INFORMATION_TECHNOLOGY,
    COMPUTER_APPLICATION_TECHNOLOGY, ELECTRICAL_ENGINEERING_AND_TECHNOLOGY, ENGINEERING_GRAPHICS_AND_DESIGN, ACCOUNTING,
    CHEMISTRY, GEOGRAPHY, HISTORY, ROBOTICS, WOOD_WORK, VISUAL_ARTS, PERFORMING_ARTS, ECONOMICS, MUSIC, HOSPITALITY,
    NUMERACY, CONSUMER_STUDIES, RELIGIOUS_STUDIES, BUSINESS_STUDIES
}