package za.co.cas;

public enum Subject {
    LANGUAGES, MATHEMATICS, PHYSICAL_SCIENCE, ACCOUNTING, CHEMISTRY, GEOGRAPHY, HISTORY, INFORMATION_TECHNOLOGY,
    BIOLOGY, ARCHITECTURE, ELECTRICAL_ENGINEERING, WOOD_WORK
}