package za.co.cas;

public enum Subject {
    FIRST_LANGUAGE, SECOND_LANGUAGE, MATHEMATICS, PHYSICAL_SCIENCE, ACCOUNTING, CHEMISTRY, GEOGRAPHY,
    HISTORY, INFORMATION_TECHNOLOGY, BIOLOGY, ARCHITECTURAL_SCIENCE, ELECTRICAL_SCIENCE, ROBOTICS,
    WOOD_WORK, BUSINESS_STUDIES, ARTS
}